Refactor codebase
rosnovsky/bwwcraft.com pull request #11
Opened 2020-09-08 21:20 UTC by dillionmegida

- use prettier to format the codebase based on the configurations
- break the homepage into components
- group components in a better way

2020-09-09 15:59 UTC, rosnovsky requested changes
A few little extra tasks, if you're up for it :)

2020-09-09 15:59 UTC, rosnovsky commented on src/components/Portfolio/index.js
> +    return (
Thank you, @dillionmegida! Could you please turn this into a functional component?

2020-09-09 15:59 UTC, rosnovsky commented on src/components/Nav/index.js
> +    return (
Could you turn this into a functional component as well?

It may be worth turning scroller into a helper/wrapper. I don't expect you to do this necessarily, but if you could give it a shot, I'd appreciate this effort.

2020-09-09 21:43 UTC, dillionmegida commented on src/components/Nav/index.js
> +    return (
I think being a utility is okay like that. An implementation I would have done rather than this was to add the logic it to the home page component, but I guess this simplifies it enough and it's more readable

What do you think?

2020-09-11 03:03 UTC, rosnovsky approved these changes

2020-09-11 03:03 UTC, merged